# Note:  Hyperparameters have been changed slightly from
# the paper to allow for things to easily run on 1 GPU

BASE_TASK_CONFIG_PATH: "configs/tasks/pointnav_mp3d_medium.yaml"
TRAINER_NAME: "bc"
ENV_NAME: "NavRLEnv"
SIMULATOR_GPU_ID: 0
TORCH_GPU_ID: 0
#VIDEO_OPTION: []
VIDEO_OPTION: ["disk"]  # Can be uncommented to generate videos.
TENSORBOARD_DIR: "tb"
VIDEO_DIR: "video_dir"
TEST_EPISODE_COUNT: -1  # Evaluate on all episodes if -1
EVAL_CKPT_PATH_DIR: "data/new_checkpoints"
NUM_PROCESSES: 1
SENSORS: ["DEPTH_SENSOR"]
CHECKPOINT_FOLDER: "data/new_checkpoints"
NUM_UPDATES: 1_000_000
LOG_INTERVAL: 25
CHECKPOINT_INTERVAL: 2000
SEED:  1  # Sets Gym, PyTorch and Numpy seeds

RL:
  POLICY:
    name: "PointNavResNetPolicy"
  BC:
    used_inputs: ["position", "heading_vec"]
    LOAD_FULL_DATASET: True  # Load full dataset
    EVAL_FREQ: 5000  # How often (time steps) we evaluate
    eval_episodes: 20  # How many episodes run during evaluation
    LOAD_MODEL: ""  # Model load file name, "" doesn't load
    batch_size: 256  # Batch size for all networks
    DISCOUNT: 0.99  # Discount factor
    # BC
    BUFFER_SIZE:  2_000_000  # Replay buffer size
    FRAC: 1.0  # Best data fraction to use
    MAX_TRAJ_LEN: 500  # Max trajectory length
    NORMALIZE: True  # Normalize states
    ignore_stop: True
    load_full_dataset: True

# Wandb logging
PROJECT: "habitat"
GROUP: "BC-habitat"
NAME: "BC"

MODEL:
  # selecting inputs to use
  used_inputs: ["position", "heading", "pointgoal"]
  ablate_depth: False
  ablate_rgb: False
  num_recurrent_layers: 2
  rnn_type: "GRU"
  backbone: "resnet18"
  resnet_baseplanes: 32
  normalize_visual_inputs: False
  force_blind_policy: False
  embed_sge: True
  embed_goal_seg: False
  sem_seg_pred: True
  NO_VISION: False
  USE_SEMANTICS: False
  USE_PRED_SEMANTICS: False
  SWITCH_TO_PRED_SEMANTICS_UPDATE: 0
#  SEMANTIC_ENCODER:
#    rednet_ckpt: "data/rednet-models/rednet_semmap_mp3d_tuned.pth"
#    cnn_type: "ResnetSemSegEncoder"
#    output_size: 256
#    backbone: "resnet18"
#    train_encoder: True
#    embedding_size: 4
#    is_thda: False
#    num_classes: 29
  RGB_ENCODER:
    cnn_type: "ResnetRGBEncoder"
    output_size: 256
    backbone: "resnet18"
    train_encoder: True
  DEPTH_ENCODER:
    cnn_type: "VlnResnetDepthEncoder"
    output_size: 128
    backbone: "resnet50"
    trainable: False
    ddppo_checkpoint: "data/ddppo-models/gibson-2plus-resnet50.pth"
  STATE_ENCODER:
    hidden_size: 2048
    rnn_type: "GRU"
    num_recurrent_layers: 2
  SEQ2SEQ:
    use_prev_action: True
  PROGRESS_MONITOR:
    use: False
