BASE_TASK_CONFIG_PATH: "configs/tasks/pointnav_mp3d_medium.yaml"
ENV_NAME: "NavRLEnv"
SIMULATOR_GPU_ID: 0
TORCH_GPU_ID: 0
#VIDEO_OPTION: []
VIDEO_OPTION: ["disk"]  # Can be uncommented to generate videos.
TENSORBOARD_DIR: "tb"
VIDEO_DIR: "video_dir"
EVAL_CKPT_PATH_DIR: "data/new_checkpoints/bc"
NUM_PROCESSES: 1
SENSORS: ["DEPTH_SENSOR"]
CHECKPOINT_FOLDER: "data/new_checkpoints/bc"
SEED:  1  # Sets Gym, PyTorch and Numpy seeds

RL:
  POLICY:
    name: "PointNavResNetPolicy"
  BC:
    used_inputs: ["position", "heading_vec"]
    LOAD_FULL_DATASET: True  # Load full dataset
    EVAL_FREQ: 5000  # How often (time steps) we evaluate
    eval_episodes: 20  # How many episodes run during evaluation
    LOAD_MODEL: ""  # Model load file name, "" doesn't load
    batch_size: 256  # Batch size for all networks
    DISCOUNT: 0.99  # Discount factor
    # BC
    FRAC: 1.0  # Best data fraction to use
    MAX_TRAJ_LEN: 1000  # Max trajectory length
    NORMALIZE: True  # Normalize states
    ignore_stop: False
    load_full_dataset: True
    continuous: False
    learning_rate: 0.0003

# Wandb logging
PROJECT: "habitat"
GROUP: "BC-habitat"
NAME: "BC"
WANDB_KEY: "88503bf83ff0a806be0ebc012f36e98fb193348a"

MODEL:
  # selecting inputs to use
  used_inputs: ["position", "heading", "pointgoal"]
