# Note:  Hyperparameters have been changed slightly from
# the paper to allow for things to easily run on 1 GPU

BASE_TASK_CONFIG_PATH: "configs/tasks/pointnav_mp3d_medium.yaml"
TRAINER_NAME: "bc"
ENV_NAME: "NavRLEnv"
SIMULATOR_GPU_ID: 0
TORCH_GPU_ID: 0
#VIDEO_OPTION: []
VIDEO_OPTION: ["disk"]  # Can be uncommented to generate videos.
TENSORBOARD_DIR: "tb"
VIDEO_DIR: "video_dir"
TEST_EPISODE_COUNT: -1  # Evaluate on all episodes if -1
EVAL_CKPT_PATH_DIR: "data/new_checkpoints/dt"
NUM_PROCESSES: 1
SENSORS: ["DEPTH_SENSOR"]
CHECKPOINT_FOLDER: "data/new_checkpoints/dt"
NUM_UPDATES: 1_000_000
LOG_INTERVAL: 25
CHECKPOINT_INTERVAL: 2000
SEED:  1  # Sets Gym, PyTorch and Numpy seeds

RL:
  POLICY:
    name: "PointNavResNetPolicy"
  DT:
    # model params
    embedding_dim: 128
    num_layers: 3
    num_heads: 1
    seq_len: 20
    episode_len: 1000
    attention_dropout: 0.1
    residual_dropout: 0.1
    embedding_dropout: 0.1
    max_action: 1
    # training params
    learning_rate: 0.0001
    betas: (0.9, 0.999)
    weight_decay: 0.0001
    clip_grad: 0.25
    batch_size: 4096
#    batch_size: 1
    update_steps: 100_000
    warmup_steps: 10_000
    reward_scale: 0.001
#    num_workers: 1
    num_workers: 4
    # evaluation params
#    target_returns: (12000.0, 6000.0)
    target_returns: (1.0)
    eval_episodes: 1
    eval_every: 1_000
    # general params
    deterministic_torch: False
    train_seed: 10
    eval_seed: 42
#    device: "cuda"
    ignore_stop: True
    # TODO: single_goal = True

# Wandb logging
PROJECT: "habitat"
GROUP: "DT-habitat"
NAME: "DT"
WANDB_KEY: "88503bf83ff0a806be0ebc012f36e98fb193348a"

MODEL:
  # selecting inputs to use
  used_inputs: ["position", "heading", "goal_position"]
  ablate_depth: False
  ablate_rgb: False
  num_recurrent_layers: 2
  rnn_type: "GRU"
  backbone: "resnet18"
  resnet_baseplanes: 32
  normalize_visual_inputs: False
  force_blind_policy: False
  embed_sge: True
  embed_goal_seg: False
  sem_seg_pred: True
  NO_VISION: False
  USE_SEMANTICS: False
  USE_PRED_SEMANTICS: False
  SWITCH_TO_PRED_SEMANTICS_UPDATE: 0
#  SEMANTIC_ENCODER:
#    rednet_ckpt: "data/rednet-models/rednet_semmap_mp3d_tuned.pth"
#    cnn_type: "ResnetSemSegEncoder"
#    output_size: 256
#    backbone: "resnet18"
#    train_encoder: True
#    embedding_size: 4
#    is_thda: False
#    num_classes: 29
  RGB_ENCODER:
    cnn_type: "ResnetRGBEncoder"
    output_size: 256
    backbone: "resnet18"
    train_encoder: True
  DEPTH_ENCODER:
    cnn_type: "VlnResnetDepthEncoder"
    output_size: 128
    backbone: "resnet50"
    trainable: False
    ddppo_checkpoint: "data/ddppo-models/gibson-2plus-resnet50.pth"
  STATE_ENCODER:
    hidden_size: 2048
    rnn_type: "GRU"
    num_recurrent_layers: 2
  SEQ2SEQ:
    use_prev_action: True
  PROGRESS_MONITOR:
    use: False
