ENVIRONMENT:
  MAX_EPISODE_STEPS: 500
SIMULATOR:
  AGENT_0:
    SENSORS: ['DEPTH_SENSOR']
#    SENSORS: []
  HABITAT_SIM_V0:
    GPU_DEVICE_ID: 0
  DEPTH_SENSOR:
    WIDTH: 640
    HEIGHT: 480
    HFOV: 79
    MIN_DEPTH: 0.5
    MAX_DEPTH: 5.0
    POSITION: [0, 0.88, 0]
  TURN_ANGLE: 30
  FORWARD_STEP_SIZE: 0.25

TASK:
  TYPE: Nav-v0
  SUCCESS_DISTANCE: 0.2

  SENSORS: ['GPS_SENSOR', 'POINTGOAL_SENSOR', "HEADING_SENSOR", "POINTGOAL_WITH_GPS_COMPASS_SENSOR"]
  POINTGOAL_WITH_GPS_COMPASS_SENSOR:
    GOAL_FORMAT: "POLAR"
    DIMENSIONALITY: 3
  GOAL_SENSOR_UUID: pointgoal_with_gps_compass
  POINTGOAL_SENSOR:
      GOAL_FORMAT: "POLAR"
      DIMENSIONALITY: 3
  GPS_SENSOR:
      GOAL_FORMAT: "POLAR"
      DIMENSIONALITY: 3


#  MEASUREMENTS: ['DISTANCE_TO_GOAL', 'SUCCESS', 'SPL', 'SOFT_SPL', 'TOP_DOWN_MAP']
  MEASUREMENTS: ['DISTANCE_TO_GOAL', 'SUCCESS', 'SPL', 'SOFT_SPL']
  SUCCESS:
    SUCCESS_DISTANCE: 0.2
DATASET:
  EPISODES: -1  # Number of episodes to train on
  TYPE: PointNav-v1
  SPLIT: train
  DATA_PATH: data/datasets/pointnav/mp3d/v1/{split}/{split}.json.gz
  SP_DATASET_PATH: data/sp_datasets/datasets_medium_no_depth.hdf5
#  SP_DATASET_PATH: data/sp_datasets/datasets_medium.hdf5
  CONTENT_SCENES: ["17DRP5sb8fy"] # medium scene
